version: '3.8'

  backend:
    image: node:20.15.1
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"